export const  REQUEST_CALENDAR_DATA = 'REQUEST_CALENDAR_DATA';
export const SET_CALENDAR_EVENTS = 'SET_CALENDAR_EVENTS';
export const CALENDARS_RECEIVED = 'CALENDARS_RECEIVED';
export const ERROR_ENCOUNTERED = 'ERROR_ENCOUNTERED';
