export const  REQUEST_CALENDAR_DATA = 'REQUEST_CALENDAR_DATA';
export const CALENDAR_EVENTS_RECEIVED = 'CALENDAR_EVENTS_RECEIVED';
export const CALENDARS_RECEIVED = 'CALENDARS_RECEIVED';
export const ERROR_ENCOUNTERED = 'ERROR_ENCOUNTERED';
